version: '3.9'
services:
  php:
    build: .
    working_dir: /app
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=canoe_user
      - POSTGRES_PASSWORD=strong_password
      - POSTGRES_DB=canoe
  rabbitmq:
    image: rabbitmq:3.9.29
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_password
