version: '3.9'
services:
  composer:
    build: .
    working_dir: /app
    command: ["composer", "install", "--no-progress", "--no-interaction"]
    volumes:
      - .:/app
  web:
    build: .
    working_dir: /app
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
      - rabbitmq
      - migrations
  consumer:
    build: .
    working_dir: /app
    command: ["php", "bin/console", "messenger:consume", "async", "-vv"]
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - database
      - rabbitmq
  migrations:
    depends_on:
      - database
    build: .
    working_dir: /app
    command: ["php", "bin/console", "doctrine:migrations:migrate", "--no-interaction"]
    restart: on-failure
    volumes:
      - .:/app
  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=canoe_user
      - POSTGRES_PASSWORD=strong_password
      - POSTGRES_DB=canoe
  rabbitmq:
    image: rabbitmq:3.9.29
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_password
